version: "3.1"
services: 
  nginx:
    container_name: projeto_nginx
    build: 
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "3001:80"
    depends_on: 
      - php
    networks: 
      - laravel

  php:
    container_name: projeto_php
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:9000"
    networks: 
      - laravel

networks:
  laravel:
    driver: bridge
